### ISSUE TITLE
Training on new data

### ISSUE THREAD

**Issue by jagadeeshraja** [grantjenks/wordsegment#2]
Hi,
 It would be great if you can add the feature to use your algorithm to train on any new data. The google trillion data is a bit old and if we need anything domain specific, it may not be the best dataset to train.

**Comment by grantjenks** [comment]
This isn't tough. Let me make a blog post-type article about it. What dataset interests you? I'd love to use a more modern corpus.

**Comment by grantjenks** [comment]
Just released v0.5.3 and added these notes: http://www.grantjenks.com/docs/wordsegment/using-a-different-corpus.html
