### ISSUE TITLE
`exhilarate` does not segment as expected

### ISSUE THREAD

**Issue by mooosu** [grantjenks/wordsegment#21]
`echo exhilarate | python -m wordsegment`
output:

exhi la rate

**Comment by grantjenks** [comment]
*Shrug*. I guess it's not a very common word. Only the top 330,000 unigrams are included from the internet. You can teach wordsegment new words though:

1. Google: "exhilarate" and observe 1.88e6 results.
2. Google: "apple" and observe 5.44e9 results.
3. Use that ratio to estimate the count for "exhilarate" at the time the corpus was created.

Here's an example:

```
In [1]: import wordsegment

In [2]: wordsegment.load()

In [3]: wordsegment.segment('exhilarate')
Out[3]: ['exhi', 'la', 'rate']

In [4]: 'exhilarate' in wordsegment.UNIGRAMS
Out[4]: False

In [5]: 'apple' in wordsegment.UNIGRAMS
Out[5]: True

In [6]: wordsegment.UNIGRAMS['apple']
Out[6]: 50551171.0

In [7]: wordsegment.UNIGRAMS['exhilarate'] = wordsegment.UNIGRAMS['apple'] * 1.88e6 / 5.44e9

In [8]: wordsegment.UNIGRAMS['exhilarate']
Out[8]: 17469.889977941177

In [9]: wordsegment.segment('exhilarate')
Out[9]: ['exhilarate']
```
