### ISSUE TITLE
russian language

### ISSUE THREAD

**Issue by vinnitu** [grantjenks/wordsegment#29]
Hi!

What I need to do to train model on russian language?

**Comment by grantjenks** [comment]
Replace the UNIGRAMS and BIGRAMS variables with Russian word sets. Then change clean() to remove non-Russian characters.

**Comment by grantjenks** [comment]
There’s an example in the docs for a custom corpus: http://www.grantjenks.com/docs/wordsegment/using-a-different-corpus.html
