### ISSUE TITLE
'helloworld' does not segment as expected

### ISSUE THREAD

**Issue by Forest216** [grantjenks/wordsegment#35]
It seems that the string 'helloworld' can not be segmented,while the string 'helloeveryone' can be segmented correctly.

**Comment by grantjenks** [comment]
Look in the unigrams dictionary. It’s probably there.

**Comment by grantjenks** [comment]
Yep, it’s there. Occurs 145,066 times in the internet corpus used.

**Comment by Forest216** [comment]
> 是的，它在那里。在使用的互联网语料库中出现 145,066 次。

Thanks a lot
