### ISSUE TITLE
Words segmenting in one direction, but not another.

### ISSUE THREAD

**Issue by vrunhofen** [grantjenks/wordsegment#37]
Consider:
```python
segment('treeparticle')
segment('particletree')
```

The first one segments correctly. It outputs:` ['tree', 'particle']` ; but the second one never segments! It returns `['particletree']`. Even when I put a space in between them. It always outputs `['particletree']`.

  I don't get it. Why? And how do I fix this?

**Comment by grantjenks** [comment]
I don’t know. Try looking at the unigrams and bigrams and checking the counts for the words your expecting.

Maybe “particletree” is in the unigrams. The corpus is based on the internet and a quick Google search shows that “particletree” is a website …
