### ISSUE TITLE
Only Old word 

### ISSUE THREAD

**Issue by aongwachi** [grantjenks/wordsegment#6]

**Comment by grantjenks** [comment]
I'm a bit confused. What do you want?

**Comment by aongwachi** [comment]
thank you for reply me, sorry for my english skill
i have a problem about word in file unigrams.txt because the word is to new.
example ,i want to split 'ironman' to 'iron','man' but 'ironman' is exists in  unigrams.txt 
my solution is remove 'ironman' from unigrams.txt .

**Comment by grantjenks** [comment]
That's a valid solution. You can delete words from the dictionary that you do not want. You can also add new words. The documentation describes how.

Unfortunately, there is only one corpus that ships with wordsegment. I'm open to including others if they are reasonably sized. I'm also open to other languages. But I don't have an "old word" dictionary myself.

**Comment by aongwachi** [comment]
thank you for explain me
