### ISSUE TITLE
Recursion limit exceeded 

### ISSUE THREAD

**Issue by ChristosChristofidis** [grantjenks/wordsegment#7]
Sometimes it pops up Exception saying Recursion limit exceeded  ? Is that intended or?

**Comment by grantjenks** [comment]
Can you provide an example where that happens?

**Comment by Jarvisr** [comment]
I am facing same problem. @grantjenks  What is maximum length of text we can pass to wordsegment.segment() function?

**Comment by grantjenks** [comment]
I tested that once and recall something like 500 characters. How long is your text?

**Comment by Jarvisr** [comment]
It works great for  approximate 3500 char. I tested it. But I am using it for web text so it's pretty long. To solve this char length problem I divided text into 3000(for safety) char chunk and then merge these chunks to get final string so it works for me now. If you have any suggestion tell me I love try it.

**Comment by grantjenks** [comment]
Wow. I didn't know it could go that high.

Two possible fixes:

1. Change the algorithm to not use recursion. (Sounds hard.)
2. Split long chunks into smaller chunks and combine the result. (Your method.)

I like option (2) as well. If it's reusable, feel free to share your code with a pull request.

**Comment by Jarvisr** [comment]
I have try to resolve text limit problem. I tried up to 20k chars and it works like gem (take some time).

**Comment by grantjenks** [comment]
Fixed at d032edb and deployed at v0.8.0.

There is also now an "isegment" function which returns an iterator of segmented words. You may find that useful for long texts.
